approvedGitRepositories:
  - "**"

checksumBehavior: throw

enableHardenedMode: true

enableScripts: true

injectEnvironmentFiles:
  - .env?

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FONTAWESOME_NPM_AUTH_TOKEN:-}"
    npmRegistryServer: "https://npm.fontawesome.com/"
