nodeLinker: node-modules

injectEnvironmentFiles:
  - .env?

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: ${FONTAWESOME_NPM_AUTH_TOKEN}
