name: Ensure ENV
description: 'Ensures the provided ENV var is set'

inputs:
  env-key:
    description: 'The key to ensure is present'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Confirm ENV
      env:
        ENV_KEY: ${{ inputs.env-key }}
      run: |
        if [[ -z "${!ENV_KEY:-}" ]]; then
          echo "Did not find non-empty $ENV_KEY in the ENV"
          exit 1
        fi
      shell: bash
