name: Lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

jobs:
  lint:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup environment
        uses: ./.github/actions/setup_environment

      - name: Lint JavaScript/TypeScript
        run: yarn lint:js

      - name: Check formatting
        run: yarn format:check

      - name: Lint CSS/SCSS
        run: yarn lint:css --quiet
