name: "Run Nightly Percy Tests"
on: [push, pull_request]
  # schedule:
  #   - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.17.4'
      - run: npm config set "@fortawesome:registry" https://npm.fontawesome.com/
      - run: npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_NPM_AUTH_TOKEN
      - name: Install
        run: yarn
      - run: npm install -g wait-on
      - run: yarn storybook & wait-on http://localhost:9009
      - name: Percy Test
        uses: percy/exec-action@v0.3.1
        with:
          command: "cypress run"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
