name: "Prepare hotfix"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: true

jobs:
  prepare-hotfix:
    name: Prepare hotfix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14.17.4'

      - name: Create hotfix branch
        run: git checkout -b hotfix/${{ github.event.inputs.version }}

      - name: Initialize mandatory git config
        uses: fregante/setup-git-user@v1

      - name: Bump version in package.json
        run: yarn version --new-version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Commit manifest files
        id: make-commit
        run: |
          git add package.json
          git commit --message "Prepare hotfix ${{ github.event.inputs.version }}"

          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Publish hotfix branch
        run: git push origin hotfix/${{ github.event.inputs.version }}

      - name: Merge hotfix into main branch
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: hotfix/${{ github.event.inputs.version }}
          base: main
          title: Merge hotfix/${{ github.event.inputs.version }} into main branch

      - name: Merge hotfix into develop branch
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: hotfix/${{ github.event.inputs.version }}
          base: develop
          title: Merge hotfix/${{ github.event.inputs.version }} into develop branch

